### ISSUE TITLE
"Can't open display" with centos7 minimal installation

### ISSUE THREAD

**Issue by Kcetry** [l3pp4rd/st#1]
St running successful in centos7 with gnome ,but I run it  fail  with minimal installation after installing X window system, libX11, libXft,libXext which it require and it display "can't open display".
There are some situations in minimal
1. run
`DESKTOP=:0.0`
`sudo X`
X server start successful.
2.`startx`
It said ~/xauth's some files not found
3.'systemctl isolate graphical.target'
It said 'PolicyKit daemon disconnected from the bus,We are no longer a registered authentication agent'
4.run xclock(an X11 program) successful
What should I do?

**Comment by setkeh** [comment]
What happens if you run 

`DISPLAY=:0 st`

That should force it to connect to display 0

also can you paste the output from 

`echo $DISPLAY`

and

`cat /var/log/Xorg.0.log`

And possibly your xorg.conf that may give us some more info as to what you issue is :)

**Comment by l3pp4rd** [comment]
thanks for your help @setkeh 
@Kcetry that is unusual, DISPLAY should always default to 0. Maybe the user you start **st** with, does not have these defaults loaded into his shell environment.

**Comment by Kcetry** [comment]
Thanks for help! @setkeh  @l3pp4rd  I have solved this problem.The reason is that I haven't install window manager which X server use when it start.Then,I installed dwm and st,also,edited the `~/.xinitrc`,and run `startx` successful.I have to said,the suckless's software is slim but powerful,Thanks again.  ^.^

**Comment by l3pp4rd** [comment]
glad you solved it @Kcetry never had any crash with this software. you can also use **slim** as login manager and **dmenu** to launch applications.

**Comment by setkeh** [comment]
Im glad you solved it mate :) Glad to lend a hand good luck :D
