### ISSUE TITLE
Shift key not working

### ISSUE THREAD

**Issue by sillykelvin** [l3pp4rd/st#3]
I use SHIFT key to switch the input method, but it seems not work when only single SHIFT key pressed, the input method does not change.

**Comment by l3pp4rd** [comment]
Hi, well I do not understand what you mean by `switch the input`. If that relates to locale binding switch, you need to configure the binding in [config.h](https://github.com/l3pp4rd/st/blob/master/config.h#L137) and create a proper command which is able to switch whatever you prefer. This is not a terminal for common use cases, these are my own configurations which I use personally. For everyone else, it needs to be configured based on their use cases.

**Comment by sillykelvin** [comment]
Thanks for your reply.
